### ISSUE TITLE
not completed?

### ISSUE THREAD

**Issue by shinriyo** [samdmarshall/GraphQL.nim#1]
I guess it is port from `libgraphqlparser`

So, installed it

```
nimble install https://github.com/samdmarshall/GraphQL.nim
```

but

```
import graphql
```
 
```
var users = graphql_parse_string(User)
```
didn't use.

is it work now?

**Comment by samdmarshall** [comment]
I thought this was completed, but I may not have finished a DSL to wrap the queries. iirc this was never published as part of the nimble package manager so it doesn't have any official support.

**Comment by samdmarshall** [comment]
looking over the code, arguably this should all work as a wrapper around libgraphqlparser. I don't see any obvious reason why it wouldn't work?? as previously mentioned i never released this through the nimble package manager so i didn't want to formally provide support for this beyond my own personal usage.

**Comment by timotheecour** [comment]
ok, thanks, if you added a small hello-world-like example that would help a lot !

**Comment by genotrance** [comment]
I just created [nimgraphql](https://github.com/genotrance/nimgraphql) using nimgen. I had tried to do this a year ago but nimgen wasn't capable enough to handle the mangling back then.
